name: Createrepo

on:
  workflow_call:
    inputs:
      oc-version:
        required: true
        type: string
      os-version:
        required: true
        type: string
      arch:
        required: true
        type: string
      repo:
        required: true
        type: string

concurrency:
  group: ${{ inputs.repo }}/${{ inputs.os-version }}/${{ inputs.oc-version }}/${{ inputs.arch }}
  cancel-in-progress: false

jobs:
  createrepo:
    runs-on: ubuntu-latest
    env:
      s3path: ${{ inputs.repo }}/${{ inputs.os-version }}/${{ inputs.oc-version }}/${{ inputs.arch }}
    steps:
      - name: test
        run: echo ${{ inputs.repo }}/${{ inputs.os-version }}/${{ inputs.oc-version }}/${{ inputs.arch }}
      - name: test
        run: echo ${s3path}
