name: Test

on:
  push:

concurrency:
  group: opencast-createrepo
  cancel-in-progress: false

env:
  OC_VERSION: 14

jobs:
  build:
    strategy:
      matrix:
        osversion:
          - 7
          - 8
          - 9
    outputs:
      oc-version: ${{ steps.version.outputs.version }}
    name: createrepo (el${{ matrix.osversion }}, ${{ matrix.repo }}/${{ matrix.arch }})
    runs-on: ubuntu-latest
    steps:

      - id: version
        run: echo "version=${{ env.OC_VERSION }}" >> $GITHUB_OUTPUT

      - name: hello world
        run: >
          echo hello world

  createrepo:
    uses: lkiesow/workflow_call_test/.github/workflows/createrepo.yml@main
    needs: build
    strategy:
      matrix:
        os-version:
          - 7
          - 8
          - 9
    with:
      oc-version: ${{ needs.build.outputs.oc-version }}
      os-version: ${{ matrix.os-version }}
      arch: noarch
      repo: testing
